spring.application.name=Backend
server.port=3000

spring.datasource.url=${DB_URL}
spring.datasource.password=${DB_PASS}
spring.datasource.username=${DB_USER}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=classpath:db/changelog/001-create-users-table.sql
spring.liquibase.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

security.jwt.secret-key=${JWT_SECRET}
security.jwt.expiration-time=${JWT_EXP}