spring.application.name=Backend
server.port=3000

spring.datasource.url=${DB_URL}
spring.datasource.password=${DB_PASS}
spring.datasource.username=${DB_USER}

spring.flyway.locations=classpath:db/migration
spring.flyway.enabled=false